name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for App
    - working-directory: src/ 
      run: docker build .
    - name: Build the Docker image for db
    - working-directory: postgres/
      run: docker build .
